INSERT INTO question (questiontittle, option1, option2, option3, option4,rightanswer, difficultylevel,category)
VALUES ('Which Java Keyword is used to create a sublass?', 'class', 'interface', 'extends','implements', 'extends',
        'Easy','Java'),
       ('Which of the following option leads to the portability and security of Java?', 'Bytecode is executed by JVM', 'The applet makes the Java code secure and portable', 'Use of exception handling','Dynamic binding between objects', 'Bytecode is executed by JVM',
        'Easy','Java'),
       ('Which of the following is not a Java features?', 'Dynamic', 'Architecture Neutral', 'Use of pointers','Object-oriented', 'Use of pointers',
        'Easy','Java'),
       ('The \u0021 article referred to as a ?', 'Unicode escape sequence', 'Octal escape', 'Hexadecimal','Line feed', 'Unicode escape sequence',
        'Easy','Java'),
       (' _____ is used to find and fix bugs in the Java programs.', 'JVM', 'JVM', 'JDK','JDB', 'JDB',
        'Easy','Java'),
       ('What is the return type of the hashCode() method in the Object class?', 'Object', 'int', 'long','void', 'int',
        'Easy','Java'),
       ('Which of the following is a valid long literal?', 'ABH8097', 'L990023', '904423','0xnf029L', '0xnf029L',
        'Hard','Java'),
       ('Who developed Python Programming Language?', 'Wick van Rossum', 'Rasmus Lerdorf', 'Guido van Rossum','Niene Stom', ' Guido van Rossum',
        'Hard','Python'),
       ('Which type of Programming does Python support?', 'object-oriented programming', 'structured programming', 'functional programming','all of the mentioned', 'all of the mentioned',
        'Hard','Python'),
       ('Is Python code compiled or interpreted?', 'Python code is both compiled and interpreted', 'Python code is neither compiled nor interpreted', 'Python code is only compiled','Python code is only interpreted', 'Python code is both compiled and interpreted',
        'Easy','Python');